Add theme font sizes
Automattic/course pull request #19
Opened 2022-10-05 21:13 UTC by gabrielcaires

# Introduced changes
* Add all theme font sizes

## Testing instructions:
* Create a page
* Copy and past the following post content

```

<h1>I am THE H1 TAG</h1>

<h2>I am the H2 tag</h2>

<h3>I am the H3</h3>

<h4>I am the H4</h4>

<h4>I am the h5</h4>

<h6>I am the h6</h6>

<p>This blog is run by Professor Jean Biche, Chair of Art History at Sacré-Cœur Université Paris. He joined the Department of Art in 2009 moving from the University of Notredame where he was a Professor of Global History and Culture.</p>

<h1 class="has-large-font-size">group/section titles</h1>

<h1 class="has-x-large-font-size">posts titles on grid</h1>

<h1 class="has-xx-large-font-size">POST TITLES ON LISTS</h1>

<h1 class="has-4-x-large-font-size">DISPLAY TITLE</h1>

```

2022-10-07 09:16 UTC, LavaGolem commented
Here are the issues I found: 
**H1**
1. It is the smallest: 
Edit: 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7208249/194518860-1031e3f4-3b0e-42f9-bf45-ca1edc723986.png">
Preview: 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/7208249/194518932-f7e4dddf-af57-46aa-8c73-549ca2eb282d.png">

**Title**
Title has wrong font in preview (in edit it is a correct font but small)
Edit:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/7208249/194519093-67a13120-46e7-42e8-b73b-b164ff048a13.png">

Preview: 
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7208249/194519130-abac885a-f29d-4320-b8cb-fef3c9ac6c80.png">

2022-10-07 09:16 UTC, LavaGolem requested changes
Here are the issues I found: 
**H1**
1. It is the smallest: 
Edit: 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7208249/194518860-1031e3f4-3b0e-42f9-bf45-ca1edc723986.png">
Preview: 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/7208249/194518932-f7e4dddf-af57-46aa-8c73-549ca2eb282d.png">

**Title**
Title has wrong font in preview (in edit it is a correct font but small)
Edit:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/7208249/194519093-67a13120-46e7-42e8-b73b-b164ff048a13.png">

Preview: 
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7208249/194519130-abac885a-f29d-4320-b8cb-fef3c9ac6c80.png">

2022-10-07 09:17 UTC, LavaGolem reviewed
The **paragraph** text is too small 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/7208249/194519461-1f2e57e9-f9b9-47cd-9c69-84b293ec138d.png">

2022-10-07 09:18 UTC, LavaGolem commented on theme.json
> +					"fontSize": "var(--wp--preset--font-size--3x-large)",
this one is not correct. It should be: 

``` "fontSize": "var(--wp--preset--font-size--3-x-large)", ```

This fixes the h1 size

2022-10-10 20:08 UTC, gabrielcaires commented on theme.json
> +					"fontSize": "var(--wp--preset--font-size--3x-large)",
Fixed here https://github.com/Automattic/sensei-theme/pull/19/commits/7098138269d2b636fc1b2658419f79765aa47bc8

2022-10-11 10:47 UTC, LavaGolem approved these changes

2022-10-11 12:16 UTC, merged